### ISSUE TITLE
Set Typhoeus max concurrency

### ISSUE THREAD

**Issue by revett** [dblooman/linkey-ruby#21]
### Problem

Concurrent requests are DOSing the target site.
### Solution

Allow the user to set a `max_concurrent_requests` option, to limit how many requests happen in parallel. 

Change this line: [lib/linkey.rb#L100](https://github.com/DaveBlooman/linkey/blob/master/lib/linkey.rb#L100)

https://github.com/typhoeus/typhoeus#specifying-max-concurrency

**Comment by JakeChampion** [comment]
:+1: I accidentally took down a fellow students project using linkey.
