### ISSUE TITLE
Error while running linkey on windows machine

### ISSUE THREAD

**Issue by khana25** [dblooman/linkey-ruby#23]
Hi @DaveBlooman I'm trying to run the linkey from the command linke on windows machine.

I have installed all the required gems and the files. I have created a yaml files to test the status of the links of my website. 

While running the command:  linkey smoke path/to_config.yaml_file

I'm getting this error:

 (LoadError)b/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `<module:Curl>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:8:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon.rb:15:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/linkey-1.5.0/lib/linkey.rb:3:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/linkey-1.5.0/lib/linkey/cli.rb:2:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/linkey-1.5.0/bin/linkey:4:in `<top (required)>'
        from D:/Ruby22/bin/linkey:23:in `load'
        from D:/Ruby22/bin/linkey:23:in `<main>'

Could you please help me how to get rid of it and start running the linkey smoothly on my windows machine?

Many Thanks 
Ayub Khan

**Comment by dblooman** [comment]
I think you need the development kit(Dev Kit) as well on ruby - https://rubyinstaller.org/downloads/

**Comment by khana25** [comment]
@DaveBlooman  After installing the DevKit, now I'm getting the same error:  

ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.

Ruby version:
ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]

Linkey:  linkey-1.5.0

And the devKit bin folder path has been specified in the Environmental Variables

**Comment by dblooman** [comment]
You will need to install `curl`, download and unzip -https://curl.haxx.se/download.html.  You will then need to add the location of the unzipped folder to your path

**Comment by khana25** [comment]
Curl has been downloaded and the location is added to, still I'm getting the same error after closing and re-open the command prompt and running the command: linkey smoke config.yaml 

The error is:

 (LoadError)b/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `<module:Curl>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:8:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon.rb:15:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/linkey-1.5.0/lib/linkey.rb:3:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/linkey-1.5.0/lib/linkey/cli.rb:2:in `<top (required)>'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from D:/Ruby22/lib/ruby/gems/2.2.0/gems/linkey-1.5.0/bin/linkey:4:in `<top (required)>'
        from D:/Ruby22/bin/linkey:23:in `load'
        from D:/Ruby22/bin/linkey:23:in `<main>'
