### ISSUE TITLE
Make locating bad requests easier

### ISSUE THREAD

**Issue by JakeChampion** [dblooman/linkey-ruby#6]
```
As a developer
When using Linkey
I would like to be able to easily identify the bad links
```

Maybe we could store the bad requests in an array and then log it out as a table after all the links have been parsed?

**Comment by dblooman** [comment]
What do you think the output should be?  A new md file using some sort of template table, or perhaps a simple HTML file?

**Comment by JakeChampion** [comment]
Just in the log I think, like codesniffer does.
